### ISSUE TITLE
Shop freezes the game trying to display something

### ISSUE THREAD

**Issue by nikovaan** [3snowp7im/SotN-Randomizer#2]
Seed: 1555609681843
Trying to scroll the shop items down past Velvet Hat freezes the game, forcing a reboot.
Conveniently there is a library card extremely early to make verifying faster.

Emulator used:  bizhawk 2.3.0

**Comment by 3snowp7im** [comment]
Should be fixed in https://github.com/3snowp7im/SotN-Item-Randomizer/commit/cb7d005712a5448e156e0364f069a5b14e263c58
